function m = localMass(Am,rho,Lm,t)
%LOCALMASS
%    M = LOCALMASS(AM,RHO,LM,T)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    26-Apr-2014 22:13:15

t2 = cos(t);
t3 = t2.^2;
t4 = t.*2.0;
t5 = sin(t4);
t6 = Am.*Lm.*rho.*t5.*(1.0./6.0);
t7 = sin(t);
t8 = Am.*Lm.*rho.*t5.*(1.0./1.2e1);
t9 = t7.^2;
t10 = Am.*Lm.*rho.*t3.*(1.0./6.0);
t11 = Am.*Lm.*rho.*t3.*(1.0./3.0);
t12 = Am.*Lm.*rho.*t9.*(1.0./6.0);
t13 = Am.*Lm.*rho.*t9.*(1.0./3.0);
m = reshape([t11,t6,t10,t8,t6,t13,t8,t12,t10,t8,t11,t6,t8,t12,t6,t13],[4, 4]);
